name: Test Docker

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: windows-latest
    steps:
      - name: Check WSL
        run: wsl --update

      - name: Win / Set WSL 2 as default
        run: wsl --set-default-version 2

      - name: Download rabbitmq
        run: docker pull rabbitmq