name: Test Docker

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: windows-latest
    steps:
      - name: Check WSL
        run: wsl --update

      - name: Win / Set WSL 2 as default
        run: |
          wsl --list --online
          wsl --install -d Ubuntu
          wsl --set-default-version 2
          wsl --list

      - name: Start Docker Desktop
        run: |
          Start-Service docker
          docker version
        shell: pwsh
  
      - name: Download rabbitmq
        run: docker pull rabbitmq