name: Pipeline Check

on:
  workflow_run:
    workflows: ["huavanthong/microservice-golang/Microservice Golang"]  # Thay "Your Pipeline Name" bằng tên của pipeline bạn quan tâm
    types:
      - completed

jobs:
  check-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Check Pipeline Result
        run: |
          # Lấy kết quả của pipeline từ API GitHub
          result=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/jobs")

          # Kiểm tra kết quả của pipeline (thay đổi logic dựa trên định dạng kết quả)
          if echo "$result" | jq -e '.jobs[].conclusion' | grep -q 'failure'; then
            echo "Pipeline failed."
            exit 1
          else
            echo "Pipeline passed."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
