name: Release

on:
  push:
    tags:
      - "*"

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  display-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variable in job A
        run: echo "MY_ENV_VAR=example_value_hello" >> $GITHUB_ENV
        
  update-control-file:
    name: Update content
    runs-on: ubuntu-latest
    needs: [display-variables]
    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set Up Git User
      run: |
        git config user.email "huavanthong14@gmail.com"
        git config user.name "Thong Hua"

    - name: Update contents
      run: |
        echo tag-$(date +%d.%m.%Y-%H.%M.%S) > content.txt 
      
    - name: Commit Changes
      run: |
        tag_version=$(cat content.txt)
        tag_branch=htv3hc/feat/$tag_version
        echo $tag_branch > tag_branch.txt

        git checkout -b $tag_branch
        git add content.txt
        git commit -m "Auto commit from GitHub Actions"
        git push -u origin $tag_branch

    - name: Create Pull Request
      run: |
        tag_branch=$(cat tag_branch.txt)
        gh pr create --base master --head $tag_branch --title "Auto-generated PR" --body "This PR was automatically generated by GitHub Actions."


  call-build-process:
    uses: ./.github/workflows/build.yml
