name: Release

on:
  push:
    tags:
      - "*"

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  display-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variable in job A
        run: echo "MY_ENV_VAR=example_value_hello" >> $GITHUB_ENV
  
  # call-build-process:
  #   needs: [display-variables]
  #   uses: ./.github/workflows/build.yml
      
  update-control-file:
    name: Update content
    runs-on: ubuntu-latest
    # needs: [call-build-process]
    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set Up Git User
      run: |
        git config user.email "huavanthong14@gmail.com"
        git config user.name "Thong Hua"

    - name: Checkout automation branch
      run: |
        tag_branch=htv3hc/feat/tag-version-0.0.2
        echo $tag_branch > tag_branch.txt
    
        git checkout -b $tag_branch  

    - name: Update contents
      run: |
        echo tag-$(date +%d.%m.%Y-%H.%M.%S) > content.txt
      
    - name: Commit Changes
      run: |
        tag_branch=$(cat tag_branch.txt)
        git add content.txt
        git commit -m "Auto commit from GitHub Actions"
        git push -u -f origin $tag_branch

    - name: Create Pull Request
      run: |
        tag_branch=$(cat tag_branch.txt)
        # Github CLI for pull request.
        gh pr create \
        --base master --head $tag_branch \
        --title "Auto-generated PR" \
        --body "This PR was automatically generated by GitHub Actions." \
        --assignee huavanthong \
        --reviewer huavanthong


