name: RabbitMQ Example

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pull RabbitMQ Docker image
      run: |
        docker pull micdenny/rabbitmq-windows

    - name: Start RabbitMQ container
      shell: bash
      run: |
        docker run -d --hostname my-rabbit --name some-rabbit micdenny/rabbitmq-windows

    - name: Check RabbitMQ status
      run: |
        docker ps -a

    - name: Run tests against RabbitMQ
      run: |
        # Example: Use a script or test framework to interact with RabbitMQ
        # Replace with your actual test commands
        docker exec rabbitmq rabbitmqctl list_queues

    - name: Stop RabbitMQ container
      run: |
        docker stop rabbitmq
        docker rm rabbitmq
